export const MARKER_SPRITE_X_OFFSET = 29;
export const MARKER_SPRITE_Y_OFFSET = 50;
export const MARKER_SPRITE_POSITION = {
  A0: [0, 0],
  B0: [MARKER_SPRITE_X_OFFSET, 0],
  C0: [MARKER_SPRITE_X_OFFSET * 2, 0],
  D0: [MARKER_SPRITE_X_OFFSET * 3, 0],
  E0: [MARKER_SPRITE_X_OFFSET * 4, 0],
  F0: [MARKER_SPRITE_X_OFFSET * 5, 0],
  G0: [MARKER_SPRITE_X_OFFSET * 6, 0],
  H0: [MARKER_SPRITE_X_OFFSET * 7, 0],
  I0: [MARKER_SPRITE_X_OFFSET * 8, 0],
  A1: [0, MARKER_SPRITE_Y_OFFSET],
  B1: [MARKER_SPRITE_X_OFFSET, MARKER_SPRITE_Y_OFFSET],
  C1: [MARKER_SPRITE_X_OFFSET * 2, MARKER_SPRITE_Y_OFFSET],
  D1: [MARKER_SPRITE_X_OFFSET * 3, MARKER_SPRITE_Y_OFFSET],
  E1: [MARKER_SPRITE_X_OFFSET * 4, MARKER_SPRITE_Y_OFFSET],
  F1: [MARKER_SPRITE_X_OFFSET * 5, MARKER_SPRITE_Y_OFFSET],
  G1: [MARKER_SPRITE_X_OFFSET * 6, MARKER_SPRITE_Y_OFFSET],
  H1: [MARKER_SPRITE_X_OFFSET * 7, MARKER_SPRITE_Y_OFFSET],
  I1: [MARKER_SPRITE_X_OFFSET * 8, MARKER_SPRITE_Y_OFFSET],
  A2: [0, MARKER_SPRITE_Y_OFFSET * 2],
  B2: [MARKER_SPRITE_X_OFFSET, MARKER_SPRITE_Y_OFFSET * 2],
  C2: [MARKER_SPRITE_X_OFFSET * 2, MARKER_SPRITE_Y_OFFSET * 2],
  D2: [MARKER_SPRITE_X_OFFSET * 3, MARKER_SPRITE_Y_OFFSET * 2],
  E2: [MARKER_SPRITE_X_OFFSET * 4, MARKER_SPRITE_Y_OFFSET * 2],
  F2: [MARKER_SPRITE_X_OFFSET * 5, MARKER_SPRITE_Y_OFFSET * 2],
  G2: [MARKER_SPRITE_X_OFFSET * 6, MARKER_SPRITE_Y_OFFSET * 2],
  H2: [MARKER_SPRITE_X_OFFSET * 7, MARKER_SPRITE_Y_OFFSET * 2],
  I2: [MARKER_SPRITE_X_OFFSET * 8, MARKER_SPRITE_Y_OFFSET * 2],
};
export const MARKER_DATA = [
  {
    title: '편의시설 1',
    type: '편의시설',
    position: { lat: 37.3595704, lng: 127.105399 },
  },
  {
    title: '편의시설 2',
    type: '편의시설',
    position: { lat: 37.36, lng: 127.106 },
  },
  { title: '식당 1', type: '식당', position: { lat: 37.361, lng: 127.107 } },
  // 더 많은 마커 데이터...
];
